/// Flutter icons Arrow
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Arrow
///      fonts:
///       - asset: fonts/Arrow.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Arrow {
  Arrow._();

  static const _kFontFam = 'Arrow';

  static const IconData button_onboarding = IconData(0xe801, fontFamily: _kFontFam);
}
