/// Flutter icons DeinOrt
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DeinOrt
///      fonts:
///       - asset: fonts/DeinOrt.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DeinOrt {
  DeinOrt._();

  static const _kFontFam = 'DeinOrt';

  static const IconData icon_dein_ort = IconData(0xe800, fontFamily: _kFontFam);
}
