/// Flutter icons FAQ
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FAQ
///      fonts:
///       - asset: fonts/FAQ.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FAQ {
  FAQ._();

  static const _kFontFam = 'FAQ';

  static const IconData icon_faq = IconData(0xe802, fontFamily: _kFontFam);
}
