/// Flutter icons Feed
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Feed
///      fonts:
///       - asset: fonts/Feed.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Feed {
  Feed._();

  static const _kFontFam = 'Feed';

  static const IconData icon_feed = IconData(0xe803, fontFamily: _kFontFam);
}
