/// Flutter icons PlayButton
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PlayButton
///      fonts:
///       - asset: fonts/PlayButton.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PlayButton {
  PlayButton._();

  static const _kFontFam = 'PlayButton';

  static const IconData play_taste = IconData(0xe807, fontFamily: _kFontFam);
}
