/// Flutter icons Podcast
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Podcast
///      fonts:
///       - asset: fonts/Podcast.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Podcast {
  Podcast._();

  static const _kFontFam = 'Podcast';

  static const IconData podcast = IconData(0xe808, fontFamily: _kFontFam);
}
